export default {
  breakpoint: 610,
  headerHeight: 63,
  headerBreakpoint: 710,
  blogMaxWidth: 650,
  baseColor: "#34A7B2",
  secondaryColor: "#F59AA3",
  lightBackgroundColor: "#F5E4C3",
  darkBackgroundColor: "#5B2E35",
  darkBackgroundTextColor: "#F5E4C3",
  darkBackgroundLinkHoverColor: "#F59AA3",
  titleColor: "#34A7B2",
  textColor: "#5B2E35",
  workplaceTitle: "#34A7B2",
  titleFont: "Museo Sans",
  textFont: "Museo Slab",
}
